#!/usr/bin/env node
/*
 * Generates an offline-first service worker for the Flutter web build.
 *
 * Flutter 3.44+ ships a service worker that merely unregisters itself
 * (see https://github.com/flutter/flutter/issues/156910), so the framework no
 * longer provides offline caching. Flutter's bootstrap still *registers*
 * `flutter_service_worker.js`, so we overwrite that file with a real
 * precaching worker. The result: once the app has loaded online, every asset
 * it needs is cached and the game is fully playable in airplane mode.
 *
 * Usage: node tool/gen_service_worker.js [buildDir]   (default: build/web)
 */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const buildDir = path.resolve(process.argv[2] || 'build/web');
const swName = 'flutter_service_worker.js';

if (!fs.existsSync(buildDir)) {
  console.error(`Build directory not found: ${buildDir}`);
  console.error('Run `flutter build web` first.');
  process.exit(1);
}

// Collect every file to precache, relative to the build root, skipping the
// service worker itself and bulky debug symbol files that aren't needed at
// runtime.
function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

const files = walk(buildDir)
  .map((f) => path.relative(buildDir, f).split(path.sep).join('/'))
  .filter((f) => f !== swName)
  .filter((f) => !f.endsWith('.symbols'))
  // Skip dotfiles (e.g. .last_build_id) — not needed at runtime.
  .filter((f) => !f.split('/').pop().startsWith('.'))
  .sort();

// Per-file content hash, plus an overall version used to name the cache.
const resources = {};
const overall = crypto.createHash('sha1');
for (const rel of files) {
  const buf = fs.readFileSync(path.join(buildDir, rel));
  const hash = crypto.createHash('md5').update(buf).digest('hex');
  resources[rel] = hash;
  overall.update(rel).update(hash);
}
const version = overall.digest('hex').slice(0, 12);

// The app shell that must always resolve, including the navigation root "/".
const coreList = ['./', 'index.html', 'main.dart.js', 'flutter.js',
  'flutter_bootstrap.js', 'manifest.json'].filter(
  (c) => c === './' || resources[c] !== undefined,
);

const sw = `'use strict';
// GENERATED by tool/gen_service_worker.js. Offline-first cache for Wordled.
const CACHE_NAME = 'wordled-cache-${version}';
const RESOURCES = ${JSON.stringify(resources, null, 2)};
const CORE = ${JSON.stringify(coreList)};

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // Precache each resource independently. Using cache.addAll() would abort the
    // entire install if any single request failed, silently breaking offline
    // support; allSettled caches everything that succeeds instead.
    await Promise.allSettled(
      Object.keys(RESOURCES).map(async (key) => {
        try {
          const response = await fetch(new Request(key, { cache: 'reload' }));
          if (response && response.ok) await cache.put(key, response);
        } catch (err) {
          // Ignore individual failures; the fetch handler falls back to network.
        }
      })
    );
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  // Only ever cache/serve same-origin GETs; cross-origin requests are left to
  // the network untouched so the worker can't be used as an open proxy.
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Serve navigations from the cached app shell so the game opens offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('index.html').then((r) => r || fetch(request))
    );
    return;
  }

  // Cache-first for everything else; fall back to network and populate cache.
  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const response = await fetch(request);
      if (response && response.status === 200 && response.type === 'basic') {
        const cache = await caches.open(CACHE_NAME);
        cache.put(request, response.clone());
      }
      return response;
    } catch (err) {
      const fallback = await caches.match('index.html');
      if (fallback) return fallback;
      throw err;
    }
  })());
});
`;

fs.writeFileSync(path.join(buildDir, swName), sw);
console.log(
  `Wrote ${swName}: ${files.length} resources cached, version ${version}.`
);
